name: devops test

on:
  push:
    branches: [ frontend, backend ]

env:
  # Use the same ssh-agent socket value across all jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  frontend-deploy:
    if: github.ref == 'refs/heads/frontend'
    name: Deploy to K8S frontend
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew docker

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.PASSWORD }}


      - name: Push Frontend Docker image
        uses: actions-hub/docker@master
        with:
          args: push 706com/frontend:1.1

      - name: restart frontend container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.0.112
          username: test
          key: ${{ secrets.SSH_KEY }}
          port: 8102
          script: |
            kubectl apply -f - <<EOF
            apiVersion: v1
            kind: Pod
            metadata:
              name: frontend
            spec:
              containers:
                - name: frontend
                  image: 706com/frontend:1.1
            EOF
  backend-deploy:
    if: github.ref == 'refs/heads/backend'
    name: Deploy to K8S backend
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew docker -Pplatform=backend

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Push Backend Docker image
        uses: actions-hub/docker@master
        with:
          args: push 706com/backend:1.1

#      - name: Set up SSH agent
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}
#          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
      - name: Setup SSH with a passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: restart backend container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.0.112
          username: test
#          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }} # cuz same password
          port: 8102
          script: |
            kubectl apply -f - <<EOF
            apiVersion: v1
            kind: Pod
            metadata:
              name: backend
            spec:
              containers:
                - name: backend
                  image: 706com/backend:1.1
            EOF

